"""Add target_environment to Project

Revision ID: 099c477010de
Revises: 
Create Date: 2025-04-18 20:31:10.303464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099c477010de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('target_environment', sa.String(), nullable=False))
    op.create_index(op.f('ix_project_target_environment'), 'project', ['target_environment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_target_environment'), table_name='project')
    op.drop_column('project', 'target_environment')
    # ### end Alembic commands ###
